#!/bin/sh
[ "$(git branch --show-current)" != "main" ] && exit 0

echo "Running linter..."
pnpm tsc --noEmit && pnpm lint --fix

if [ $? -ne 0 ]; then
  echo "Lint failed, push aborted."
  exit 1
fi

if ! git diff --quiet; then
  echo "Lint auto-fixed some files. Push aborted."
  exit 1
fi

echo "Running tests..."
pnpm test

if [ $? -ne 0 ]; then
  echo "Tests failed, push aborted."
  exit 1
fi