#!/bin/sh
echo "Running linter..."
pnpm tsc --noEmit && pnpm lint --fix
if [ $? -ne 0 ]; then
  echo "Lint failed, push aborted."
  exit 1
fi

if ! git diff --quiet; then
  echo "Lint auto-fixed some files. Push aborted."
  exit 1
fi